POST http://localhost:3000/signup HTTP/1.1
Host:localhost
Content-Type:application/json
{
    "firstName":"sivagnanasuntharam",
    "lastName":"piriyaraj",
    "email":"piriyaraj1998@gmail.com",
    "password":"piriyaraj"
}


# GET http://localhost:3000/ HTTP/1.1